# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BucketListIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BucketListIOS
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  
  #pod 'GoogleSignIn'
  pod 'FirebaseUI'
  
  #pod 'FBSDKLoginKit'
  #pod 'FBSDKCoreKit'

#pod 'FirebaseUI/Auth'

#pod 'FirebaseUI/Google'
#pod 'FirebaseUI/Facebook'
#pod 'FirebaseUI/Twitter'
#pod 'FirebaseUI/Phone'

end
